<div class="page-heading"><div><p class="eyebrow">Chatbots</p><h1>Conversations</h1><p class="muted">Production and test transcripts are clearly separated and loaded in bounded pages.</p></div><a class="button button-quiet" href="/admin/conversations/analytics">View analytics</a></div>
<?php if (is_string($message) && $message !== ''): ?><div class="alert alert-success" role="status"><?= $escape($message) ?></div><?php endif; ?>
<form class="panel filter-panel compact-filter-panel" method="get" action="/admin/conversations">
    <div class="filter-heading"><div><h2>Find conversations</h2><p>Search a session reference or filter by chatbot, traffic, state, and activity date.</p></div><a class="text-link" href="/admin/conversations">Clear filters</a></div>
    <div class="filter-grid">
        <label class="filter-field filter-field-wide"><span>Session reference</span><input name="search" value="<?= $escape($query->search ?? '') ?>" maxlength="64"></label>
        <label class="filter-field"><span>Chatbot</span><select name="chatbot_id"><option value="">All chatbots</option><?php foreach ($chatbots as $option): ?><option value="<?= $escape($option['id']) ?>" <?= $query->chatbotId === $option['id'] ? 'selected' : '' ?>><?= $escape($option['name']) ?></option><?php endforeach; ?></select></label>
        <label class="filter-field"><span>Traffic</span><select name="traffic"><option value="">All traffic</option><option value="production" <?= $query->isTest === false ? 'selected' : '' ?>>Production</option><option value="test" <?= $query->isTest === true ? 'selected' : '' ?>>Test</option></select></label>
        <label class="filter-field"><span>Status</span><select name="status"><option value="">All states</option><?php foreach (\App\Domain\Chatbots\ChatbotSessionStatus::cases() as $status): ?><option value="<?= $status->value ?>" <?= $query->status === $status ? 'selected' : '' ?>><?= $escape(ucfirst($status->value)) ?></option><?php endforeach; ?></select></label>
        <label class="filter-field"><span>Activity from</span><input type="date" name="date_from" value="<?= $escape($query->dateFrom ?? '') ?>"></label>
        <label class="filter-field"><span>Activity to</span><input type="date" name="date_to" value="<?= $escape($query->dateTo ?? '') ?>"></label>
        <label class="filter-field"><span>Sort</span><select name="sort"><?php foreach (['activity' => 'Last activity', 'started' => 'Started', 'messages' => 'Messages', 'usage' => 'Provider usage'] as $value => $label): ?><option value="<?= $value ?>" <?= $query->sort === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></label>
        <label class="filter-field"><span>Results</span><select name="per_page"><?php foreach ($query->pagination->allowedPageSizes() as $size): ?><option value="<?= $size ?>" <?= $query->pagination->perPage === $size ? 'selected' : '' ?>><?= $size ?></option><?php endforeach; ?></select></label>
    </div><div class="filter-actions"><button class="button button-primary" type="submit">Apply filters</button></div>
</form>
<div class="result-toolbar"><p><?= $page->total === 0 ? 'No conversations' : 'Showing ' . $escape($page->from()) . '–' . $escape($page->to()) . ' of ' . $escape($page->total) ?></p>
<form method="post" action="/admin/conversations/purge/preview"><input type="hidden" name="_csrf" value="<?= $escape($csrfToken) ?>"><?php foreach ($query->queryParameters() as $key => $value): ?><?php if ($key !== 'page'): ?><input type="hidden" name="<?= $escape($key) ?>" value="<?= $escape($value) ?>"><?php endif; ?><?php endforeach; ?><button class="button button-danger" type="submit">Review eligible purge</button></form></div>
<?php if ($page->items === []): ?><section class="empty-state"><h2>No conversations match</h2><p>Conversations appear after preview or public/integration sessions are created.</p></section><?php else: ?>
<div class="table-card"><table><thead><tr><th>Session</th><th>Chatbot</th><th>Traffic</th><th>Status</th><th>Messages</th><th>AI usage tokens</th><th>Last activity</th></tr></thead><tbody><?php foreach ($page->items as $item): ?><tr>
<td><a class="table-link" href="/admin/conversations/<?= $escape($item->publicId) ?>"><code><?= $escape($item->publicId) ?></code></a><span class="table-subtitle"><?= $escape($item->origin ?? $item->channel->value) ?></span></td>
<td><?= $escape($item->chatbotName) ?></td><td><span class="badge badge-<?= $item->isTest ? 'warning' : 'ready' ?>"><?= $item->isTest ? 'Test' : 'Production' ?></span></td><td><?= $escape(ucfirst($item->status->value)) ?></td><td><?= $escape($item->messageCount) ?></td><td><?= $escape(number_format($item->providerTokens)) ?></td><td><?= $escape($formatDate($item->lastActivityAt)) ?></td>
</tr><?php endforeach; ?></tbody></table></div><?php require dirname(__DIR__) . '/partials/list_pagination.php'; ?><?php endif; ?>
